### ISSUE TITLE
Illegal offset type in isset or empty "ilab-media-s3-tool.php"

### ISSUE THREAD

**Issue by Simoneth** [Interfacelab/ilab-media-tools#11]
Hi,
I got this error:

`PHP Warning:  Illegal offset type in isset or empty in /var/www/html/blog/wp-content/plugins/ilab-media-tools/classes/tools/s3/ilab-media-s3-tool.php on line 1012`

How could I fix it?
Thanks

**Comment by jawngee** [comment]
Are you using the plugin from the wordpress.org plugin repo?

**Comment by drhouse7** [comment]
@jawngee I've installed from WP dashboard

**Comment by drhouse7** [comment]
my error log file it's gonna to explode with all these errors 
`[Thu May 18 09:52:06.262731 2017] [:error] [pid 22669] [client 157.55.39.30:18495] PHP Warning:  Illegal offset type in isset or empty in /var/www/html/blog/wp-content/plugins/ilab-media-tools/classes/tools/s3/ilab-media-s3-tool.php on line 1012`

Is there a quick fix that I can use?

**Comment by BoxMediaUK** [comment]
Yes I have the same issue, its listed above all the images in my media library

`Warning: Illegal offset type in isset or empty in /home/xxxxx.com/public_html/wp-content/plugins/ilab-media-tools/classes/tools/s3/ilab-media-s3-tool.php on line 1012`

**Comment by jawngee** [comment]
I'll be posting an update today.  Been busy with client work.  Thanks!

Sent from my iPhone

On May 30, 2017, at 3:54 PM, Andy Wilkinson <notifications@github.com>
wrote:

Yes I have the same issue, its listed above all the images in my media
library

Warning: Illegal offset type in isset or empty in /home/
xxxxx.com/public_html/wp-content/plugins/ilab-media-tools/classes/tools/s3/ilab-media-s3-tool.php
on line 1012

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Interfacelab/ilab-media-tools/issues/11#issuecomment-304816129>,
or mute the thread

**Comment by BoxMediaUK** [comment]
Has there been an update on this?

**Comment by drhouse7** [comment]
waiting for this me too

**Comment by wedevsystem** [comment]
Hi, thanks for your great plugin and I do have facing above issue. May I know how should I fix it?

**Comment by BoxMediaUK** [comment]
Any news?

**Comment by BoxMediaUK** [comment]
I have a site full of Illegal Offset errors! Any news on anyone solving this error?

**Comment by curranabell** [comment]
Any news resolving this error? I am unable to use the wordpress importer as I am getting this error. Thank you!

**Comment by Simoneth** [comment]
A temporary solution can be found here: https://stackoverflow.com/questions/45885205/php-7-0-illegal-offset-type-in-isset-or-empty

**Comment by jawngee** [comment]
Fixed in latest commit and release.  It'll be a bit before it's up on WordPress's plugin thing.

**Comment by Simoneth** [comment]
fixed? I don't think so

**Comment by jawngee** [comment]
The f*cking fork it, fix it and send a pull request!

**Comment by JulienMelissas** [comment]
Seriously, this is open source! If you find a fix, fix it!
