### ISSUE TITLE
Uploading all folder in wp-content/uploads/

### ISSUE THREAD

**Issue by rezariazi** [Interfacelab/ilab-media-tools#125]
**Is your feature request related to a problem? Please describe.**
Other folders in wp-content/uploads/ won't be uploaded to the S3. Only folders with the following instructions
wp-content/uploads/@{date:Y/m}/@{versioning}

**Describe the solution you'd like**
I have Setup the S3 bucket and all images were uploaded to S3 as instructed below:
wp-content/uploads/@{date:Y/m}/@{versioning}
However, other folders such as buddyboss or avatar in the same folder (wp-content/uploads/) won't be uploaded to the S3.

**Describe alternatives you've considered**
I am looking for an option the setting to add any folder in the wp-content/uploads/

**Additional context**

**Comment by jawngee** [comment]
Media Cloud only uploads things that are in your media library.  It'd be impossible to do everything in your uploads folder because Media Cloud would have no way of rewriting URLs for them because it doesn't know the source.

The Pro version has integration for a few third party plugins like BuddyPress and a few others.

**Comment by rezariazi** [comment]
Hi Jawngee,
Thank you for your reply. I have purchased the pro version and the only integration I found in the documentation are:
1- WooCommerce and Easy Digital Downloads
2- Smart Slider 3
3- Elementor
4- Next Generation Gallery
5- Master Slider
Would you please provide a link or a document regarding Buddyboss(Buddypress) integration?
Thank you.
