### ISSUE TITLE
I submitted a ticket 3 days ago.

### ISSUE THREAD

**Issue by 9z3zx2Tm4SKNAGQ** [Interfacelab/ilab-media-tools#127]
Hello, I am using Pro Verison and submitted a ticket 3 days ago on https://support.mediacloud.press/. Did you check this?

**Comment by hubertnguyen** [comment]
Same here

**Comment by brown7477** [comment]
Same here!!!!

**Comment by awfmilton** [comment]
Hi, I was having the same issue. After hours of research I decided just to try deactivating and reactivating a few times, and sure enough it worked, But now I'm having issue number 66, which appears to have been raised 2 years ago. Also, what happened to the mediacloud forum?

**Comment by hubertnguyen** [comment]
Without support, I've decided that we'll unlink out WPs from mediacloud. Good luck everyone.

**Comment by jawngee** [comment]
I am back now.  I was gone for health issues.

If you still have issues, please reply to your original tickets or create new ones.

I got rid of the forums because there's only so many place I can be at one time.  In fact, I will be deleting this issue shortly because I don't want Github issues to become another forum I have to manage.

Thanks,

Jon.
