### ISSUE TITLE
Use attachment ID as prefixer

### ISSUE THREAD

**Issue by jphorn** [Interfacelab/ilab-media-tools#134]
**Describe the solution you'd like**
On the Media Cloud prefixer we like to use the attachment ID as a prefix (if it's available) and my developer @stayallive has written the following patch(es):

```patch
file:/ilab-media-tools/classes/Utilities/Prefixer.php:L142
+		$prefix = str_replace("@{id}", $id ?? 0, $prefix);
```

This is a pretty safe change to make while also considering backwards compatibility.

The other change we made that might need to be configurable or needs a new prefix tag (this change applies to `@{date}`):

```patch
file:/ilab-media-tools/classes/Utilities/Prefixer.php:L157
-				$prefix = str_replace($matches[0][$i], date($matches[1][$i]), $prefix);
+				$prefix = str_replace($matches[0][$i], $id === null ? date($matches[1][$i]) : get_the_date($matches[1][$i], $id), $prefix);
```

When uploading the attachment this change uses the attachment date as opposed to the post date (of the post where the attachment is uploaded to). This is done so our uploads are only placed in the current folders of `/wp-content/uploads/` even when the attachment is uploaded on a post from a few years ago. As you're probably aware, WordPress places uploads in the folder matching the post date and not the attachment date.

We made this change in the WordPress core (using a filter) and also applied it in `/ilab-media-tools/classes/Utilities/Prefixer.php` to keep the URL format the same to prevent confusion where the original file is.

Another solution would be is to add some filters to the `parsePrefix` method in the `Prefixer` class so we can implement them ourselves in our own code instead of needing to modify the plugin.

(full diff screenshot in GitHub: https://tny.app/osQZ0y5r)

Right now we always have to discard changes to Prefixer.php when updating Media Cloud. And unfortunately sometimes we forget, which causes all newly uploaded images to break and cause our iOS app to break down completely 'cause it's too unforgiving when image paths don't match.

**Describe alternatives you've considered**
Currently none, apart from discarding Prefixer.php when updating to new versions of Media Tools.

**Additional context**
Possibly related #71 ?

**Comment by jawngee** [comment]
Thanks for bringing this up!

I've added a filter in the next version of Media Cloud for this (based on this ticket).  My issue with any of the prefixes that use the $id is that there are a ton of cases where the $id is always going to be null.  For example, direct uploads the $id parameter will always be null.  So I'm wary of including prefixes that use it because I can see the support tickets already piling up in the help desk about how it isn't working.

However, with the filter, you can add your own custom prefix tokens and not have that worked nuked every time you update.  

It looks like this:

```php
add_filter('media-cloud/storage/prefix', function($prefix, $postId) {
	$prefix = str_replace("@{id}", $postId ?? 0, $prefix);
	return $prefix;
}, 10, 2);
```

It'll be in the next update that comes out on Monday or Tuesday (my time, GMT+7).

**Comment by jphorn** [comment]
Thank you so much! This would be extremely helpful for us. Really appreciated.

**Comment by jawngee** [comment]
This was included a couple of release ago!
