### ISSUE TITLE
Update just killed all my websites

### ISSUE THREAD

**Issue by Kiina** [Interfacelab/ilab-media-tools#16]
After the update all websites are throwing error 500 with following logs:

`2017/09/26 09:30:17 [error] 18#0: *47 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /usr/share/nginx/www/wp-content/plugins/ilab-media-tools/classes/Tools/Crop/CropTool.php on line 17" while reading response header from upstream, client: *******, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:"`

**Comment by jawngee** [comment]
What php version are you using?

**Comment by Kiina** [comment]
5.6

**Comment by jawngee** [comment]
If you are using 5.5, this plugin is only compatible with 5.6+

The line it's choking on was introduced on 5.6

**Comment by Kiina** [comment]
Oh wait it really is php 5.5. Maybe time to upgrade

**Comment by jawngee** [comment]
Yeah maybe time :)

In the meantime, you can downgrade to a previous version.  It's weird it let you update the plugin though because I put minimum php version in the readme after I refactored everything into namespaces.

1.5.3 should work fine on 5.5

https://downloads.wordpress.org/plugin/ilab-media-tools.1.5.3.zip

Sorry for the headache man!
