### ISSUE TITLE
PDFs are showing Imgix urls even when "Render PDF Files" is not checked

### ISSUE THREAD

**Issue by JulienMelissas** [Interfacelab/ilab-media-tools#20]
I have S3 and Imgix enabled. "Render PDF files" is not checked but in the media library I am seeing the attachment url go to Imgix. Imgix will try and render it, of course, but I think this is probably not desired functionality.

**Comment by infinitation** [comment]
I have the same issue. I had to write a quick php function to see if a file is pdf and then replace the imxix querystring and link with the S3 one. I haven't looked for a hook or anything within the plugin yet to see if there is an override yet.

**Comment by JulienMelissas** [comment]
@infinitation mind sharing that function and how you used it?

**Comment by JulienMelissas** [comment]
PDFs actually aren't working all-together for us right now, but I'm hoping to take a look at that next week if I can get the time.

**Comment by infinitation** [comment]
Awesome, if you need help, just let me know. We are using the roots.io system so in the sage theme we setup a function in the controller for PDF's. Since we have only one dedicated section of downloads it was easy to isolate. For future implementations we've added an ACF toggle for our client to select a "Download" feature which will run the same function. It could also be improved with the env variables. It's simple, but works :)

`function create_download($id, $imgix, $s3) {
//Get the current link based on id from ACF file field
$file = wp_get_attachment_url($id);

//Remove everything past the  querystring including the ?
$file= substr($file, 0, strpos($file, "?"));

//Replace the imgix url with the s3 url.
$file = str_replace($imgix, $s3, $file);

return $file;
}`

**Comment by jawngee** [comment]
The issue is with the pdf library I’m using, I think.  

https://github.com/smalot/pdfparser <https://github.com/smalot/pdfparser>

It would be a place to start looking.  Also if you are using roots/trellis, you should be able to debug this on your vagrant machine with PHPStorm very easily.

I wish I could be more help but I’m not doing much Wordpress these days, though I have a couple of gigs coming up soon.

-- 

jon gilkison
principal, interfacelab
https://linkedin.com/in/jongilkison <https://linkedin.com/in/jongilkison>
https://github.com/jawngee <https://linkedin.com/in/jongilkison>
http://interfacelab.io/ <http://interfacelab.io/>

**Comment by jawngee** [comment]
Fixed PDF uploads, at least for me ;)

The PDFParser library I was using was dying when parsing.  No error, no exception, just died.  I updated to the latest version and it has fixed it here.

Fixed PDF urls too.

**Comment by JulienMelissas** [comment]
>The PDFParser library I was using was dying when parsing. No error, no exception, just died.
This is what was happening for me too.

Everything is working for me now since the update. Thank you!
