### ISSUE TITLE
Not Compatible with EDD Free Download

### ISSUE THREAD

**Issue by Myflag** [Interfacelab/ilab-media-tools#50]
Hello again,

I discovered an issue.  The plugin is not compatible with EDD Free Downloads.  When you click to download a file it does not rewrite the URL for the file that is now on S3.  

Can you provide any assistance?

Blessings!

**Comment by jawngee** [comment]
The issue is actually with EDD Free Downloads.

Version 3.0 of this plugin is compatible with EDD itself, we spent a bit of time on that integration.  But Free Downloads doesn't use EDD's download functions, they've written their own and it's impossible for us to insert into that flow.  I can't figure out how to contact their developers to raise the issue so the 3.0 plugin will actually warn you of the incompatibility.
