### ISSUE TITLE
Not installing to WP 5.03  or WP 5.1(beta)

### ISSUE THREAD

**Issue by kiwipaulrob** [Interfacelab/ilab-media-tools#58]
Crash crash crash - help?

`Fatal error: Uncaught ChrisWhite\B2\Exceptions\B2Exception: Received error from B2: in /home/hearjjdp/public_html/wp-content/plugins/ilab-media-tools/vendor/cwhite92/b2-sdk-php/src/ErrorHandler.php:36 Stack trace: #0 /home/hearjjdp/public_html/wp-content/plugins/ilab-media-tools/vendor/cwhite92/b2-sdk-php/src/Http/Client.php(29): ChrisWhite\B2\ErrorHandler::handleErrorResponse(Object(GuzzleHttp\Psr7\Response)) #1 /home/hearjjdp/public_html/wp-content/plugins/ilab-media-tools/vendor/cwhite92/b2-sdk-php/src/Client.php(411): ChrisWhite\B2\Http\Client->request('GET', 'https://api.bac...', Array) #2 /home/hearjjdp/public_html/wp-content/plugins/ilab-media-tools/vendor/cwhite92/b2-sdk-php/src/Client.php(38): ChrisWhite\B2\Client->authorizeAccount() #3 /home/hearjjdp/public_html/wp-content/plugins/ilab-media-tools/classes/Cloud/Storage/Driver/Backblaze/BackblazeStorage.php(189): ChrisWhite\B2\Client->__construct('e9c98bdc7da6', 'K0011omOOyRjHER...') #4 /home/hearjjdp/public_html/wp-content/plugins/ilab-media-tools/classes/Cloud in /home/hearjjdp/public_html/wp-content/plugins/ilab-media-tools/vendor/cwhite92/b2-sdk-php/src/ErrorHandler.php on line 36`

**Comment by jawngee** [comment]
Your B2 credentials have expired.  I would disable the plugin and delete `ilab-media-backblaze-key` from your wp_options database.

Backblaze is some hot trash though.  We have removed support for it in 3.0 of the plugin, though it will still be available as an unsupported add-on that you can install.  I am remorseful for introducing it into the plugin in the first place.

This is something I write a lot on the support groups:

> With regards to backblaze, version 3.0 of the plugin will support pluggable service providers and backblaze is provided as an external add-on. Support has just been removed from the main plugin.
> 
> Backblaze is not a good fit for this, unless you are using it for an archive only.
> 
> The API is limited, the PHP SDKs that exist for it are poorly written and I’m not particularly motivated to put the work in for a storage provider that offers 10% of the features of the others. I’d urge you to look at something more complete like Wasabi if pricing is a sticking point for you. Google Cloud if performance is important. S3 if you are doing other AWS work.

I'm closing this since the shitty backblaze credential nonsense is fixed in 3.0 (should be available in a couple of weeks).
