### ISSUE TITLE
Support for MetaSlider

### ISSUE THREAD

**Issue by tristanbes** [Interfacelab/ilab-media-tools#72]
Hello,

Just wondering how S3 Offload media managed to support meta-slider (https://deliciousbrains.com/wp-offload-media/doc/meta-slider-integration/)  ? Is it something you want to support in a near future ?

Regards,

**Comment by jawngee** [comment]
Version 3.0 has metaslider compatibility, which is coming out sometime this month.

However, I’d personally avoid plugins that try to sidestep the standard WordPress way of doing things, which is what things like Metaslider and NextGen galleries do.  They should be working with attachments in the media library and be calling `get_attachment_src` instead of trying to be smarter than WordPress.

-- 

jon gilkison
principal, interfacelab
https://linkedin.com/in/jongilkison <https://linkedin.com/in/jongilkison>
https://github.com/jawngee <https://linkedin.com/in/jongilkison>
http://interfacelab.io/ <http://interfacelab.io/>

**Comment by tristanbes** [comment]
I agree with you, maybe you can give us some recommendation of nice plugins you'd recommend using for image gallery ?
