### ISSUE TITLE
Cropping issues

### ISSUE THREAD

**Issue by tristanbes** [Interfacelab/ilab-media-tools#76]
Hello,

This is just an assumption, but going to the cropping tool gives:

```
Access to XMLHttpRequest at 'https://s3.fr-par.scw.cloud/wp-sps-loisirs/2019/04/Accueil___Twitter-2.png' from origin 'http://tiger-jump.wordpress.vm' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

1/ Is it something to fix on the plugin side or on the S3 compliant service side ?

2/ Also, Clicking on the button "Crop" gives the use no feedback. I just thought it doesn't work until I inspected the XHR request and see it was OK.

It would be nice to offer some feedback to say the cropping has succeeded on a green background or so.

**Comment by jawngee** [comment]
Service side.  You need to enable CORS.  If it’s similar to AWS:

https://discourse.interfacelab.io/t/amazon-s3-setup/123 <https://discourse.interfacelab.io/t/amazon-s3-setup/123>

See Step 4.

IIRC, though, cropping in the 2.x version of the plugin requires the image be local, though I’m a little foggy on if that is true or not.  But you will definitely to need to enable CORS because the javascript for the crop plugin loads the image into a canvas.


-- 

jon gilkison
principal, interfacelab
https://linkedin.com/in/jongilkison <https://linkedin.com/in/jongilkison>
https://github.com/jawngee <https://linkedin.com/in/jongilkison>
http://interfacelab.io/ <http://interfacelab.io/>

**Comment by tristanbes** [comment]
Thank you. Will see if they support CORS.

**Comment by tristanbes** [comment]
Or maybe, I'll just leave this ticket open for the point numer 2/ ? as you prefer.
