### ISSUE TITLE
Deleting the media won't delete them on remote storage

### ISSUE THREAD

**Issue by tristanbes** [Interfacelab/ilab-media-tools#85]
Hello,

Deleting the media from the media library doesn't delete the file on the remote storage.

Context: https://github.com/humanmade/S3-Uploads/issues/252
caused by https://wordpress.org/support/wordpress-version/version-4-9-7/

s3 uploads fixed the problem with: https://github.com/humanmade/S3-Uploads/pull/307

**Comment by jawngee** [comment]
Thanks for the report but this has never been an issue for Media Cloud.

Humanmade uses stream wrappers so that you can use `s3://bucket/filename.png` as a filename in other functions, which is why deleting wasn't working for them because WordPress started "validating" path names and rejecting ones that don't map to a local file.  We delete files from the server outside of that whole process and there isn't any way for WordPress to interfere with that.

The only way deleting files from cloud storage wouldn't work with Media Cloud is if you don't have proper IAM permissions.

I've verified deleting from storage is working across our test rigs so I'm going to close this.  If you are seeing issues and your IAM is set up properly please feel free to re-open.
