### ISSUE TITLE
ilab media can't activate after update to the latest version

### ISSUE THREAD

**Issue by rehamwael** [Interfacelab/ilab-media-tools#96]
wordpress Version 5.2.3

Fatal error: Uncaught Error: Class 'ILAB\MediaCloud\Tools\ToolsManager' not found in /var/www/html/wp-content/plugins/ilab-media-tools/ilab-media-tools.php:176 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(286): {closure}('') #1 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /var/www/html/wp-settings.php(394): do_action('plugins_loaded') #4 /var/www/html/wp-config.php(84): require_once('/var/www/html/w...') #5 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...') #6 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...') #7 /var/www/html/wp-admin/index.php(10): require_once('/var/www/html/w...') #8 {main} thrown in /var/www/html/wp-content/plugins/ilab-media-tools/ilab-media-tools.php on line 176
The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

**Comment by jawngee** [comment]
Update how?   There's a million ways to update the plugin.

**Comment by jawngee** [comment]
Hello @rehamwael?

**Comment by regisfrias** [comment]
I got the same error after installing the plugin (fresh install, not update).

Wpackagist version works though: https://wpackagist.org/search?q=ilab-media-tools&type=any&search=

WP version 5.3.2
Media cloud 3.3.14

**Comment by erfan-ilyas** [comment]
I think your server need to to using PHP 7.1 and above.

**Comment by DavidMillington-CD** [comment]
Check your `.gitignore` file to make sure you are not ignoring anything that could cause the problem.  We had a similar issue because one of our devs added "reports" to .gitignore 2 years ago and a recent version of Media Cloud added "ReportsTool" that was inside a directory called "Reports".

The result was that the update worked locally but when we pushed the changes to our repo and deployed from there to staging then the entire site went offline with the standard WP error: _There has been a critical error on this website_.

The fix for us was to remove the "reports" line from .gitignore which allowed the new files to be pushed to the repo and deployed.
